restaurant_app/urls.py
from django.conf.urls import url
from restaurant_app import views

#template tagging
app_name = "restaurant_app"

urlpatterns=[
    # url('formpage/',views.form_view,name='form_view'),
    url('home/',views.home,name='home'),
    url('register/',views.register,name='register'),
    url('user_login/',views.user_login,name='user_login'),
    url('south/',views.south_indian_food,name='south_indian_food'),
    url('south_indian_breakfast/',views.south_indian_breakfast,name='south_indian_breakfast'),
    url('south_indian_lunch/',views.south_indian_lunch,name='south_indian_lunch'),
    url('south_indian_dinner/',views.south_indian_dinner,name='south_indian_dinner'),
    url('north/',views.north_indian_food,name='north_indian_food'),
    url('north_indian_breakfast/',views.north_indian_breakfast,name='north_indian_breakfast'),
    url('north_indian_lunch/',views.north_indian_lunch,name='north_indian_lunch'),
    url('north_indian_dinner/',views.north_indian_dinner,name='north_indian_dinner'),
    url('ordered_item/',views.ordered_item,name='ordered_item'),
    url('Orders/',views.order,name='order'),
]

restaurant_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from restaurant_app import views

urlpatterns = [
    path('',views.index,name='index'),
    # path('',views.home,name='home'),
    path('restaurant_app/',include('restaurant_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)  # the url can be blank also no needd compulsory

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True) #here photos can upload in the profile_pic folder in media directory


    def __str__(self):
        return self.user.username


class south_breakfast(models.Model):
    name=models.CharField(max_length=15)
    image=models.ImageField(upload_to='media/media/pics')
    rupees=models.IntegerField()

class south_lunch(models.Model):
    name=models.CharField(max_length=15)
    image=models.ImageField(upload_to='media/media/pics')
    rupees=models.IntegerField()

class south_dinner(models.Model):
    name=models.CharField(max_length=15)
    image=models.ImageField(upload_to='media/media/pics')
    rupees=models.IntegerField()

class north_breakfast(models.Model):
     name=models.CharField(max_length=15)
     image=models.ImageField(upload_to='media/media/pics')
     rupees=models.IntegerField()

class north_lunch(models.Model):
     name=models.CharField(max_length=15)
     image=models.ImageField(upload_to='media/media/pics')
     rupees=models.IntegerField()

class north_dinner(models.Model):
    name=models.CharField(max_length=25)
    image=models.ImageField(upload_to='media/media/pics')
    rupees=models.IntegerField()

class orders(models.Model):
    Address=models.CharField(max_length=40)
    street_name=models.CharField(max_length=40)
    phone_no=models.CharField(max_length=20)
    customer_name=models.CharField(max_length=40,default='true',blank='true')

restaurant_app/forms.py
from django import forms
from django.contrib.auth.models import User
from restaurant_app.models import UserProfileInfo
from restaurant_app.models import orders

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('email','username','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

restaurant_app/views.py
from django.shortcuts import render
from restaurant_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import south_breakfast
from .models import north_breakfast
from .models import north_lunch
from .models import south_lunch
from .models import south_dinner
from .models import north_dinner
from .models import orders

# Create your views here.
def index(request):
    return render(request,'restaurant_app/index.html')

def home(request):
    return render(request,'restaurant_app/home.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in,Nice!")

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else :
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'restaurant_app/registration.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not activated")

        else:
            print("Someone tried to login your account")
            print("they tried with this login id {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'restaurant_app/login.html', {})

def south_indian_food(request):
    return render(request,'restaurant_app/south_indian_food.html')

def north_indian_food(request):
    return render(request,'restaurant_app/north_indian_food.html')

def south_indian_breakfast(request):
    about=south_breakfast.objects.all()
    return render(request,'restaurant_app/south_indian_breakfast.html',{'about':about})

def south_indian_lunch(request):
    about=south_lunch.objects.all()
    return render(request,'restaurant_app/south_indian_lunch.html',{'about':about})

def south_indian_dinner(request):
    about=south_dinner.objects.all()
    return render(request,'restaurant_app/south_indian_dinner.html',{'about':about})

def north_indian_breakfast(request):
    about=north_breakfast.objects.all()
    return render(request,'restaurant_app/north_indian_breakfast.html',{'about':about})

def north_indian_lunch(request):
    about=north_lunch.objects.all()
    return render(request,'restaurant_app/north_indian_lunch.html',{'about':about})

def north_indian_dinner(request):
    about=north_dinner.objects.all()
    return render(request,'restaurant_app/north_indian_dinner.html',{'about':about})

def ordered_item(request):
    return render(request,'restaurant_app/ordered_item.html')

def order(request):
    Add=""
    street_name=""
    phone_no=""
    customer_name=""
    if request.method == "POST":
        Add = request.POST['address']
        street_name = request.POST['street_name']
        phone_no = request.POST['phone_no']
        customer_name = request.user.username
    orders.objects.create(Address=Add,street_name=street_name,phone_no=phone_no,customer_name=customer_name);
    return render(request,'restaurant_app/orders.html')

templates/restaurant_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charaset="utf-8">
  <title>users</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body class="bg">
  <div class="container">
    <nav class = 'navbar navbar-inverse'>
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'index' %}"></a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="navbar-link" href="{% url 'restaurant_app:register' %}">Register</a></li>

        {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a class="navbar-link" href="{% url 'restaurant_app:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>

  {% block body_block %}
  {% endblock %}

</body>
</html>

templates/restaurant_app/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>SignUp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/cursive" type="text/css"/>
</head>
<body class="bg">
  <div class="container">
    <nav class="navbar navbar-dark bg-dark">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="navbar-brand" href="#" id="home">Home</a></li>
        <li><a class="nav-link active" href="#" id="login">Login</a></li>
        <li><a class="nav-link" href="#" id="signup">SignUp</a></li>
        <!-- <li><a class="nav-link" href="#">About</a></li>
        <li><a class="nav-link" href="#">Contact Us</a></li> -->
      </ul>
    </nav>
  </div>
  <div class="container" id="con">
      <h1 class="title1">RESTAURANT</h1><br>
  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6"> <!-- column 1 -->
       <div class="thumbnail"> <!--  thumbnail 1  -->
         <img src="https://i.pinimg.com/originals/ce/cb/01/cecb013d9e66f27b2e6180b063697b59.jpg" alt="china thumbnail"> <!-- image 1 -->
         <div class="caption"> <!-- caption -->
           <h3>South Indian Food</h3>
           <p><a href="{% url 'restaurant_app:south_indian_food' %}" class="btn btn-success"role="button">Order Now</a></p>
         </div>
       </div>
     </div>
     <div class="col-md-6"> <!-- column 1 -->
        <div class="thumbnail"> <!--  thumbnail 1  -->
          <img src="https://wallpaperaccess.com/full/1316970.jpg" alt="china thumbnail"> <!-- image 1 -->
          <div class="caption">
            <h3>North Indian Food</h3>
            <p><a href="{% url 'restaurant_app:north_indian_food' %}" class="btn btn-success" role="button">Order Now</a></p>
          </div>
        </div>
      </div>
    </div>
    <footer>
      <p>About Us</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/restaurant_app/index.html
{% extends 'restaurant_app/base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
  <div class="container">
    <div class="jumbotron">
      {% if user.is_authenticated %}
        <h1 class="text-center" id="font">WELCOME TO OUR RESTAURANT🍕</h1>
        <p class="text-center" id="order"><a href="{% url 'restaurant_app:home' %}" class="btn btn-success btn-lg" role="button">Order Now</a></p>
      {% else %}
        <h2>Welcome to the site!</h2>
        {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant_app/north_indian_breakfast.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title>North Indian BreakFast</title>
  <link rel="stylesheet" href="{% static 'css/north_lunch.css' %}">
</head>
<body class="aft">
  <div class="container">
      <nav class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#"><p id="id1">Home</p></a></li>
          <li><a class="navbar-link" href="#">Contact Us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="nav-link"  onclick="https://img.icons8.com/office/2x/add-shopping-cart.png" href="{% url 'restaurant_app:ordered_item' %}"><img src="https://img.icons8.com/office/2x/add-shopping-cart.png" height="30px"><span id="cart1"></span></a></li>
        </ul>
      </nav>
  </div>
  <div class="container">
    <div class="jumbotron">
     <div class="row">
      {% for item in about %}
        {% if forloop.counter <= 3 %}
             <div class = "col-sm-6 col-md-4">
               <div class="thumbnail">
                <img class="picture" src="{{ item.image.url }}">
                <div class="caption">
                  <h3 class="text-center" id="item{{item.id}}">{{item.name}}</h3>
                  <p class="text-center" id="item1{{item.id}}">{{item.rupees}}</p>
                  <p class="text-center"><a href="#" class="btn btn-success" onclick="additem('{{item.id}}')" role="button">Order Now</a></p>
                </div>
              </div>
              </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="row">
      {% for item in about %}
        {% if forloop.counter >= 4 %}
             <div class = "col-sm-6 col-md-4">
              <div class="thumbnail">
                <img src="{{ item.image.url }}" class="img-fluid mb-2">
                <div class="caption">
                  <h3 class="text-center" id="item{{item.id}}">{{item.name}}</h3>
                  <p class="text-center"  id="item1{{item.id}}">{{item.rupees}}</p>
                  <p class="text-center"><a href="#" class="btn btn-success" onclick="additem('{{item.id}}')" role="button">Order Now</a></p>
                </div>
              </div>
            </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  </div>
  <div class="col-md-4 orders">
    <h2 class="text-center"></h2>
    <ul id="cart"></ul>
    <h4 class="text-right" id="total"></h4>
  </div>
</div>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/order.js' %}"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/restaurant_app/north_indian_food.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>north indian food</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/north_indian_food.css' %}">
</head>
<body class="bg">
  <div class="container">
    <nav class="navbar navbar-inverse">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="#"><p id="id1">Home</p></a></li>
        <li><a class="navbar-link" href="#">Contact Us</a></li>
      </ul>
    </nav>
  </div>
  <div class="container">
    <div class="jumbotron">
      <h1 class="title2">NORTH INDIAN FOODS</h1><br>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4"> <!-- column 1 -->
       <div class="thumbnail"> <!--  thumbnail 1  -->
         <img src="{% static 'css/north_breakfast.jpg' %}" alt=""> <!-- image 1 -->
         <div class="caption"> <!-- caption -->
           <h3>BreakFast</h3>
           <p><a href="{% url 'restaurant_app:north_indian_breakfast' %}" class="btn btn-success"role="button">Order Now</a></p>
         </div>
       </div>
     </div>
     <div class="col-sm-6 col-md-4"> <!-- column 1 -->
        <div class="thumbnail"> <!--  thumbnail 1  -->
          <img src="{% static 'css/north_lunch.jpg' %}" alt=""> <!-- image 1 -->
          <div class="caption">
            <h3>Lunch</h3>
            <p><a href="{% url 'restaurant_app:north_indian_lunch' %}" class="btn btn-success" role="button">Order Now</a></p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4"> <!-- column 1 -->
         <div class="thumbnail"> <!--  thumbnail 1  -->
           <img src="{% static 'css/north_dinner.jpg' %}" alt=""> <!-- image 1 -->
           <div class="caption"> <!-- caption -->
             <h3 id="id3">Dinner</h3>
             <p><a href="{% url 'restaurant_app:north_indian_dinner' %}" class="btn btn-success" role="button">Order Now</a></p>
           </div>
         </div>
       </div>
     </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/restaurant_app/ordered_item.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title>South Foods</title>
  <link rel="stylesheet" href="{% static 'css/order.css' %}">
</head>
<body class="bg">
  <div class="container">
      <nav class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#"><p id="id1">Home</p></a></li>
          <li><a class="navbar-link" href="#">Contact Us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="nav-link" onclick="https://img.icons8.com/office/2x/add-shopping-cart.png" href="{% url 'restaurant_app:ordered_item' %}"><img src="https://img.icons8.com/office/2x/add-shopping-cart.png" height="30px"><span id="cart1"></span></a></li>
        </ul>
      </nav>
  </div>
  <div class="container">
    <h1 class="text-center">BILL</h1>
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-3" id="name">
          <h3 class="text-center" id="name1">Name</h3>
        </div>
        <div class="col-md-3" id="price">
          <h3 class="text-center">Price</h3>
        </div>
        <div class="col-md-3" id="remove">
          <h3 class="text-center">Remove</h3>
        </div>
      </div>
      <div class="row" id="total">
        <h1 class="text-center">Total:</h2>
      </div>
      <div class="row" id="ordernow">
        <a href="{% url 'restaurant_app:order' %}" class="btn btn-success float-right" type="submit">Order Now</a>
      </div>
    </div>
  </div>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/cart.js' %}"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/restaurant_app/south_indian_food.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>south indian food</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/south_indian_food.css' %}">
</head>

<body class="bg">
  <div class="container">
    <nav class="navbar navbar-inverse">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="#"><p id="id1">Home</p></a></li>
        <li><a class="navbar-link" href="#">Contact Us</a></li>
      </ul>
    </nav>
  </div>
  <div class="container">
    <div class="jumbotron">
      <h1 class="title2">SOUTH INDIAN FOODS</h1><br>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4"> <!-- column 1 -->
       <div class="thumbnail"> <!--  thumbnail 1  -->
         <img src="{% static 'css/south_breakfast.jpg' %}" alt=""> <!-- image 1 -->
         <div class="caption"> <!-- caption -->
           <h3>BreakFast</h3>
           <p><a href="{% url 'restaurant_app:south_indian_breakfast' %}" class="btn btn-success"role="button">Order Now</a></p>
         </div>
       </div>
     </div>
     <div class="col-sm-6 col-md-4"> <!-- column 1 -->
        <div class="thumbnail"> <!--  thumbnail 1  -->
          <img src="{% static 'css/south_lunch.jpg' %}" alt=""> <!-- image 1 -->
          <div class="caption">
            <h3>Lunch</h3>
            <p><a href="{% url 'restaurant_app:south_indian_lunch' %}" class="btn btn-success" role="button">Order Now</a></p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4"> <!-- column 1 -->
         <div class="thumbnail"> <!--  thumbnail 1  -->
           <img src="{% static 'css/south_dinner.jpg' %}" alt=""> <!-- image 1 -->
           <div class="caption"> <!-- caption -->
             <h3 id="id3">Dinner</h3>
             <p><a href="{% url 'restaurant_app:south_indian_dinner' %}" class="btn btn-success" role="button">Order Now</a></p>
           </div>
         </div>
       </div>
     </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>